apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rfn
  name: rfn
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: rfn
status:
  loadBalancer: {}

